[2025-07-23T23:20:27.488+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: TechAndUrbanGrowth.ingestion_urbanization_data manual__2025-07-23T23:20:17.194085+00:00 [queued]>
[2025-07-23T23:20:27.644+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: TechAndUrbanGrowth.ingestion_urbanization_data manual__2025-07-23T23:20:17.194085+00:00 [queued]>
[2025-07-23T23:20:27.646+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-23T23:20:27.798+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): ingestion_urbanization_data> on 2025-07-23 23:20:17.194085+00:00
[2025-07-23T23:20:27.961+0000] {standard_task_runner.py:60} INFO - Started process 195 to run task
[2025-07-23T23:20:28.054+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'TechAndUrbanGrowth', 'ingestion_urbanization_data', 'manual__2025-07-23T23:20:17.194085+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpnksacfvb']
[2025-07-23T23:20:28.307+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask ingestion_urbanization_data
[2025-07-23T23:20:29.302+0000] {task_command.py:423} INFO - Running <TaskInstance: TechAndUrbanGrowth.ingestion_urbanization_data manual__2025-07-23T23:20:17.194085+00:00 [running]> on host 1222bc5070ab
[2025-07-23T23:20:29.613+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='TechAndUrbanGrowth' AIRFLOW_CTX_TASK_ID='ingestion_urbanization_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-23T23:20:17.194085+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-23T23:20:17.194085+00:00'
[2025-07-23T23:21:00.829+0000] {ingestion_2.py:36} ERROR - ❌ Error en urbanización: mongodb:27017: [Errno -2] Name or service not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 68816e3ddfc470603b7d3c2e, topology_type: Unknown, servers: [<ServerDescription ('mongodb', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongodb:27017: [Errno -2] Name or service not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
[2025-07-23T23:21:00.840+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-07-23T23:21:00.866+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=TechAndUrbanGrowth, task_id=ingestion_urbanization_data, execution_date=20250723T232017, start_date=20250723T232027, end_date=20250723T232100
[2025-07-23T23:21:00.933+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-07-23T23:21:01.003+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
